sudo: required

language: cpp

matrix:
  include:
    - os: linux
      services: docker
      before_install: docker pull glportal/whale-gcc
      script:
        - set -e
        - docker run -it --rm -w /data -v $(pwd):/data glportal/whale-gcc bash -c "cmake ./; make; make tests;"
        - docker run -it --rm -w /data -v $(pwd):/data glportal/whale-gcc bash -c "./external/RadixEngine/tests/SystemGraphTest ./data"
        - docker run -it --rm -w /data -v $(pwd):/data glportal/whale-gcc bash -c "./external/RadixEngine/tests/XmlReadingTest"
#    - os: osx
#      osx_image: xcode7.3
#      compiler: gcc
#      git:
#        submodules: false
#      before_install:
#        - wget "https://github.com/macports/macports-base/releases/download/v2.3.5/MacPorts-2.3.5-10.11-ElCapitan.pkg"
#        - travis_wait sudo installer -pkg MacPorts-2.3.5-10.11-ElCapitan.pkg -target /
#        - export PATH=/opt/local/bin:/opt/local/sbin:$PATH
#        - brew update
#      install:
#        - sudo port -v install bullet
#        - brew install gcc
#        - brew install assimp
#        - brew install libepoxy
#        - brew install sdl2
#        - brew install sdl2_mixer
#        - brew install bullet
#        - brew install tinyxml2
#        - brew install unittest-cpp
#        - brew install freeimage
#      before_script:
#        - git submodule update --init --recursive
#        - mkdir build && cd build
#        - export CC=gcc-6 CXX=g++-6
#      script:
#        - cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=$PWD/install ..
#        - make -j4
    - os: osx
      osx_image: xcode7.3
      compiler: clang
      git:
        submodules: false
      before_install:
        - wget "https://github.com/macports/macports-base/releases/download/v2.3.5/MacPorts-2.3.5-10.11-ElCapitan.pkg"
        - travis_wait sudo installer -pkg MacPorts-2.3.5-10.11-ElCapitan.pkg -target /
        - export PATH=/opt/local/bin:/opt/local/sbin:$PATH
        - brew update
      install:
        - sudo port -v install bullet
        - brew install assimp
        - brew install libepoxy
        - brew install sdl2
        - brew install sdl2_mixer
        - brew install bullet
        - brew install tinyxml2
        - brew install unittest-cpp
        - brew install freeimage
      before_script:
        - git submodule update --init --recursive
        - mkdir build && cd build
      script:
        - cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=$PWD/install ..
        - make -j4

notifications:
  irc: "chat.freenode.net#glportal"
